#!/usr/bin/env ruby

# This file was placed here by GitLab. It makes sure that your pushed commits
# will be processed properly.

refs = ARGF.read
key_id  = ENV['GL_ID']
repo_path = Dir.pwd

require_relative '../lib/gitlab_custom_hook'
require_relative '../lib/gitlab_access'

if !GitlabAccess.new(repo_path, key_id, refs).exec || !GitlabCustomHook.new.pre_receive(refs, repo_path)
  exit 1
end

# @todo try to move this code into a more central location. ideally only modify
#       one file to get in our ssh pull mirroring logic and this push logic
require_relative '../perforce_swarm/mirror'
exit 1 unless PerforceSwarm::Mirror.push(refs, repo_path)
